//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportQA.Models.DTEKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHHB
    {
        public string NOHHB { get; set; }
        public string ID { get; set; }
        public string NMHHB { get; set; }
        public string ALAMAT { get; set; }
        public string KOTA { get; set; }
        public string TELP { get; set; }
        public string FAX { get; set; }
        public Nullable<decimal> TGLDIRI { get; set; }
        public string KDAREA { get; set; }
        public string NOPRS { get; set; }
        public string JENIS { get; set; }
        public string LOKASI { get; set; }
        public string GUDANG { get; set; }
        public Nullable<decimal> REG { get; set; }
        public Nullable<decimal> PANDING { get; set; }
        public Nullable<int> AKTIF { get; set; }
        public string TAMPIL { get; set; }
        public Nullable<decimal> TARGET { get; set; }
        public string NOCUST { get; set; }
        public string DEPTGL { get; set; }
        public string GRPSLS { get; set; }
        public string SRCODE { get; set; }
        public string IDPRG { get; set; }
        public string GLID { get; set; }
        public string IDAPP { get; set; }
        public Nullable<System.DateTime> BERDIRI { get; set; }
        public Nullable<decimal> POS_BEGIN { get; set; }
        public int POS_STATUS { get; set; }
        public Nullable<int> EXTRACT_STATUS { get; set; }
        public string KET { get; set; }
        public string GDG_LM { get; set; }
        public string WILAYAH { get; set; }
        public string NUSER { get; set; }
        public Nullable<System.DateTime> AUDDATE { get; set; }
        public string NEW_LOC { get; set; }
        public string GRPSLSNEW { get; set; }
        public string TYPE_FINGER { get; set; }
        public string IDKASIR { get; set; }
        public string DWDS { get; set; }
        public string CODECITY { get; set; }
        public Nullable<System.DateTime> TGLTUTUP { get; set; }
        public string PROVINCE { get; set; }
        public Nullable<decimal> LATITUDES { get; set; }
        public Nullable<decimal> LONGITUDES { get; set; }
        public string TIPE_STORE { get; set; }
    }
}
