//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportQA.Models.DTEKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICITEM
    {
        public string ITEMNO { get; set; }
        public decimal AUDTDATE { get; set; }
        public decimal AUDTTIME { get; set; }
        public string AUDTUSER { get; set; }
        public string AUDTORG { get; set; }
        public Nullable<int> ALTSET { get; set; }
        public string DESC { get; set; }
        public Nullable<decimal> DATELASTMN { get; set; }
        public Nullable<short> INACTIVE { get; set; }
        public string ITEMBRKID { get; set; }
        public string FMTITEMNO { get; set; }
        public string CATEGORY { get; set; }
        public string CNTLACCT { get; set; }
        public Nullable<short> STOCKITEM { get; set; }
        public string STOCKUNIT { get; set; }
        public string DEFPRICLST { get; set; }
        public Nullable<decimal> UNITWGT { get; set; }
        public string PICKINGSEQ { get; set; }
        public Nullable<short> SERIALNO { get; set; }
        public string COMMODIM { get; set; }
        public Nullable<decimal> DATEINACTV { get; set; }
        public string SEGMENT1 { get; set; }
        public string SEGMENT2 { get; set; }
        public string SEGMENT3 { get; set; }
        public string SEGMENT4 { get; set; }
        public string SEGMENT5 { get; set; }
        public string SEGMENT6 { get; set; }
        public string SEGMENT7 { get; set; }
        public string SEGMENT8 { get; set; }
        public string SEGMENT9 { get; set; }
        public string SEGMENT10 { get; set; }
        public string COMMENT1 { get; set; }
        public string COMMENT2 { get; set; }
        public string COMMENT3 { get; set; }
        public string COMMENT4 { get; set; }
        public Nullable<short> ALLOWONWEB { get; set; }
        public Nullable<short> KITTING { get; set; }
        public Nullable<int> VALUES { get; set; }
        public string DEFKITNO { get; set; }
        public string GUDANG { get; set; }
        public string ITEMSTORE { get; set; }
        public string JENIS { get; set; }
        public string SATACC { get; set; }
        public Nullable<decimal> CONVACC { get; set; }
        public string SATLAPOR { get; set; }
        public Nullable<decimal> CONVLAP { get; set; }
        public string SATPAKAI { get; set; }
        public Nullable<decimal> CONVPAKAI { get; set; }
        public string SATORDER { get; set; }
        public Nullable<decimal> MAX { get; set; }
        public Nullable<decimal> MIN { get; set; }
        public string OPR { get; set; }
        public Nullable<decimal> ORDER { get; set; }
        public string REPORTGRP { get; set; }
        public Nullable<decimal> TOLERANSI { get; set; }
        public string STRGUDANG { get; set; }
        public string STRPAJAK { get; set; }
        public string STRORDER { get; set; }
        public string STRPAKAI { get; set; }
        public string STRLAPOR { get; set; }
        public string TYPEITEM { get; set; }
        public string DESC1 { get; set; }
        public string ITEMAX { get; set; }
    }
}
