//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportQA.Models.DTEKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLRUSAKP
    {
        public int ID { get; set; }
        public string NORUSAK { get; set; }
        public Nullable<bool> VALIDATEE { get; set; }
        public Nullable<System.DateTime> VALIDATE_DATEE { get; set; }
    }
}
