//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportQA.Models.DTEKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLRUSAKH
    {
        public string THN { get; set; }
        public string HHB { get; set; }
        public string NORUSAK { get; set; }
        public Nullable<decimal> TGLRUSAK { get; set; }
        public string KETERANGAN { get; set; }
        public decimal AUDDATE { get; set; }
        public string AUDUSER { get; set; }
        public string AUDPOST { get; set; }
        public int POST { get; set; }
        public Nullable<bool> VALIDATE { get; set; }
        public Nullable<System.DateTime> VALIDATE_DATE { get; set; }
    }
}
