//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportQA.Models.DTEKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLRUSAKD
    {
        public string HHB { get; set; }
        public string NORUSAK { get; set; }
        public string KD_ITEM { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> KONVERSI { get; set; }
        public string KETERANGAN { get; set; }
        public decimal RECEIPT { get; set; }
    }
}
